# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField()),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionSet',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='option',
            name='option_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemanoptions.OptionSet'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set([('option_set', 'key')]),
        ),
    ]
