# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid
import swapper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
