# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import horseman.horsemanimages.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(default='', height_field='height', upload_to=horseman.horsemanimages.models.get_upload_to, verbose_name='file', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
