# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import horseman.horsemanimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0003_auto_20170223_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(height_field='height', upload_to=horseman.horsemanimages.models.get_upload_to, verbose_name='file', width_field='width'),
        ),
    ]
