# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import horseman.horsemanimages.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0004_auto_20170223_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(height_field='height', upload_to=horseman.horsemanimages.models.get_upload_to, verbose_name='file', width_field='width')),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('crop', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='hash',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendition',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemanimages.Image'),
        ),
    ]
