# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import horseman.horsemanimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0005_auto_20170223_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendition',
            name='target_height',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendition',
            name='target_width',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='hash',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='rendition',
            name='file',
            field=models.ImageField(height_field='height', upload_to=horseman.horsemanimages.models.get_rendition_upload_to, verbose_name='file', width_field='width'),
        ),
    ]
