# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0006_auto_20170223_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendition',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='horsemanimages.Image'),
        ),
    ]
