# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0007_auto_20170223_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exif_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
