# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0008_image_exif_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
