# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0009_image_captured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='captured_at_tz',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
        migrations.AlterField(
            model_name='image',
            name='captured_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
