# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0011_auto_20170227_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='wp_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
