# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0012_image_wp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rendition',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
