# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0013_auto_20170319_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rendition',
            unique_together=set([('image', 'target_width', 'target_height', 'crop')]),
        ),
    ]
