# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0016_rendition_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
