# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0017_image_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_filename',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
