# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 18:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0019_auto_20170531_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=[], size=None),
        ),
    ]
