# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0020_image_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tasks',
        ),
    ]
