# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0021_remove_image_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTask',
            fields=[
                ('task_id', models.UUIDField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemanimages.Image')),
            ],
        ),
    ]
