# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0022_imagetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetask',
            name='task_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
