# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanimages', '0023_auto_20180408_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetask',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='horsemanimages.Image'),
        ),
    ]
