# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 18:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invalidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_name', models.CharField(max_length=50)),
                ('backend', models.CharField(max_length=255)),
                ('paths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4000), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='InvalidationObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('invalidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemanfrontendcache.Invalidation')),
            ],
        ),
    ]
