# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanfrontendcache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invalidation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
