# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 19:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanfrontendcache', '0002_auto_20170331_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidation',
            name='backend_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
