# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanfrontendcache', '0003_invalidation_backend_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidation',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('error', 'Error'), ('completed', 'Completed')], default='in_progress', max_length=11),
        ),
    ]
