# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 22:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horsemanfrontendcache', '0005_auto_20170331_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidation',
            name='backend',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='invalidation',
            name='backend_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invalidation',
            name='cache_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='invalidation',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invalidation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='invalidation',
            name='paths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4000), editable=False, size=None),
        ),
        migrations.AlterField(
            model_name='invalidationobject',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='invalidationobject',
            name='invalidation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='horsemanfrontendcache.Invalidation'),
        ),
        migrations.AlterField(
            model_name='invalidationobject',
            name='object_id',
            field=models.UUIDField(editable=False),
        ),
    ]
