# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemancomments', '0002_auto_20170309_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
