# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horsemancomments', '0004_auto_20170309_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
