# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('horsemancomments', '0005_auto_20170309_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_body_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='body_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
    ]
