# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemancomments', '0008_auto_20170322_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='akismet_spam',
            field=models.NullBooleanField(default=None, editable=False),
        ),
    ]
