# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemancomments', '0010_auto_20170325_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP address'),
        ),
    ]
