# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsemannodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noderevision',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemannodes.Node'),
        ),
    ]
