# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horsemannodes', '0002_auto_20170222_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noderevision',
            name='node',
        ),
        migrations.DeleteModel(
            name='NodeRevision',
        ),
    ]
