# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsemannodes', '0013_auto_20170310_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
