# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsemannodes', '0014_auto_20170310_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderevision',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='horsemannodes.Node'),
        ),
    ]
