# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemannodes', '0015_auto_20170310_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderevision',
            name='wp_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
