# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:48
from __future__ import unicode_literals

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('horsemannodes', '0016_noderevision_wp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderevision',
            name='active',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(default=False, on=('node',)),
        ),
    ]
