# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horsemannodes', '0017_noderevision_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='modified_at',
        ),
    ]
