# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemannodes', '0019_node_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
