name: Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "8.x"

      - run: npm ci
        working-directory: ./horseman/horsemanadmin/frontend

      - run: npm run build-production
        working-directory: ./horseman/horsemanadmin/frontend

      - run: tar -czvf /tmp/django-horseman.tar.gz .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/django-horseman.tar.gz
